### PR TITLE
Add an example handler to README to help get started beginners

### PR DESCRIPTION
**Pull request by tanweerdev**

### CODE REVIEW

**Comment by gausby** [comment]
Don't worry about the decreased code coverage…coveralls seems to act up once in a while.

I think it is a good thing to have an example of a handler in the documentation, but I think it should be moved to the bottom of the example section—the following paragraph is part of connecting using the SSL transport. Please fix this and I will merge the PR.

**Comment by tanweerdev** [comment]
Sure

**Comment by gausby** [comment]
The line «Look at the `connection_test.exs`-file for more examples.» belong to the SSL example as well. Please move that up as well.

**Comment by tanweerdev** [comment]
@gausby  Done

**Comment by gausby** [comment]
Thanks

**Pull request merged**
